services:
  - type: web
    name: fpl-leaderboard-ui
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 300 --graceful-timeout 180 --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: WORKER_URL
        value: sample-url-test
      - key: ALERT_EMAIL
        value: your-email@gmail.com
      - key: SMTP_EMAIL
        value: your-smtp-email@gmail.com
      - key: SMTP_PASSWORD
        value: your-app-password
      - key: SMTP_SERVER
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
